services:
  firebird:
    image: firebirdsql/firebird
    restart: always
    ports:
      - "3051:3050"
    environment:
      - FIREBIRD_ROOT_PASSWORD=masterkey
      - FIREBIRD_USER=SYSDBA
      - FIREBIRD_PASSWORD=masterkey
      - FIREBIRD_DATABASE=banco.fdb
      - FIREBIRD_DATABASE_DEFAULT_CHARSET=UTF8
      - FIREBIRD_CONF_DataTypeCompatibility=3.0
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend-rinha

networks:
  backend-rinha:
    name: backend-rinha
    driver: bridge
