services:
  api1: &api
    image: diogoloff/rinha2025-minimo:latest
    depends_on:
      - firebird
    hostname: api1
    ports:
      - "9999:8080"
    environment:
      - DEFAULT_URL=http://payment-processor-default:8080
      - FALLBACK_URL=http://payment-processor-fallback:8080
      - DB_NAME=banco.fdb
      - DB_USER=SYSDBA
      - DB_PASS=masterkey
      - DB_HOST=firebird
      - DB_PORT=3050
      - CON_TIME_OUT=5000
      - READ_TIME_OUT=3000
      - RES_TIME_OUT=1000
      - NUM_WORKERS_FILA=24
      - NUM_WORKERS_PROCESSO=48
      - TEMPO_FILA=500
      - DEBUG=N
    volumes:
      - ./Logs/:/opt/rinha/Logs/
    networks:
      - backend-rinha
      - payment-processor	

  firebird:
    image: firebirdsql/firebird
    container_name: rinha-firebird
    ports:
      - "3050:3050"
    environment:
      - FIREBIRD_ROOT_PASSWORD=masterkey
      - FIREBIRD_USER=SYSDBA
      - FIREBIRD_PASSWORD=masterkey
      - FIREBIRD_DATABASE=banco.fdb
      - FIREBIRD_DATABASE_DEFAULT_CHARSET=UTF8
      - FIREBIRD_CONF_DataTypeCompatibility=3.0
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend-rinha

networks:
  backend-rinha:
    name: backend-rinha
    driver: bridge
  payment-processor:
    external: true
