services:
  nginx:
    image: nginx:1.25-alpine
    container_name: rinha-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    networks:
      - backend-rinha
      - payment-processor
    #deploy:
    #  resources:
    #    limits:
    #      cpus: "0.20"
    #      memory: "15MB"

  api1: &api
    image: diogoloff/rinha2025-minimo:latest
    hostname: api1
    environment:
      - DEFAULT_URL=http://payment-processor-default:8080
      - FALLBACK_URL=http://payment-processor-fallback:8080
      - DB_NAME=banco.fdb
      - DB_USER=SYSDBA
      - DB_PASS=masterkey
      - DB_HOST=firebird
      - DB_PORT=3050
      - CON_TIME_OUT=50
      - READ_TIME_OUT=100
      - RES_TIME_OUT=200
      - NUM_WORKERS=10
      - DEBUG=S
    networks:
      - backend-rinha
      - payment-processor	

  api2:
    <<: *api
    hostname: api2
    environment:
      - DEFAULT_URL=http://payment-processor-default:8080
      - FALLBACK_URL=http://payment-processor-fallback:8080
      - DB_NAME=banco.fdb
      - DB_USER=SYSDBA
      - DB_PASS=masterkey
      - DB_HOST=firebird
      - DB_PORT=3050
      - CON_TIME_OUT=50
      - READ_TIME_OUT=100
      - RES_TIME_OUT=200
      - NUM_WORKERS=10
      - DEBUG=S

  firebird:
    image: firebirdsql/firebird
    container_name: rinha-firebird
    ports:
      - "3050:3050"
    environment:
      - FIREBIRD_ROOT_PASSWORD=masterkey
      - FIREBIRD_USER=SYSDBA
      - FIREBIRD_PASSWORD=masterkey
      - FIREBIRD_DATABASE=banco.fdb
      - FIREBIRD_DATABASE_DEFAULT_CHARSET=UTF8
      - FIREBIRD_CONF_DataTypeCompatibility=3.0
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend-rinha
    #deploy:
    #  resources:
    #    limits:
    #      cpus: "0.50"
    #      memory: "160MB"

networks:
  backend-rinha:
    name: backend-rinha
    driver: bridge
  payment-processor:
    external: true
