services:
  nginx:
    image: nginx:1.25-alpine
    container_name: rinha-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    networks:
      - backend-rinha
      - payment-processor
    #deploy:
      #resources:
        #limits:
          #cpus: "0.10"
          #memory: "10MB"

  api1: &api
    image: diogoloff/rinha2025-minimo:latest
    depends_on:
      - firebird
    hostname: api1
    environment:
      - DEFAULT_URL=http://payment-processor-default:8080
      - FALLBACK_URL=http://payment-processor-fallback:8080
      - DB_NAME=banco.fdb
      - DB_USER=SYSDBA
      - DB_PASS=masterkey
      - DB_HOST=firebird
      - DB_PORT=3050
      - NUM_WORKERS_FILA=32
      - NUM_WORKERS_PROCESSO=32
      - NUM_TENTATIVAS_DEFAULT=3
      - READ_TIME_OUT=5500
      - TEMPO_FILA=1000
      - DEBUG=N
    volumes:
      - ./Logs/:/opt/rinha/Logs/
    networks:
      - backend-rinha
      - payment-processor

  api2:
    <<: *api
    hostname: api2
    volumes:
      - ./Logs2/:/opt/rinha/Logs/

  firebird:
    image: firebirdsql/firebird
    container_name: rinha-firebird
    ports:
      - "3050:3050"
    environment:
      - FIREBIRD_ROOT_PASSWORD=masterkey
      - FIREBIRD_USER=SYSDBA
      - FIREBIRD_PASSWORD=masterkey
      - FIREBIRD_DATABASE=banco.fdb
      - FIREBIRD_DATABASE_DEFAULT_CHARSET=UTF8
      - FIREBIRD_CONF_DataTypeCompatibility=3.0
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend-rinha

networks:
  backend-rinha:
    name: backend-rinha
    driver: bridge
  payment-processor:
    external: true
