services:
  nginx:
    image: nginx:1.25-alpine
    container_name: rinha-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    networks:
      - backend-rinha
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "20MB"

  api1: &api
    image: diogoloff/rinha2025-minimo:latest
    depends_on:
      - firebird
    hostname: api1
    environment:
      - DEFAULT_URL=http://payment-processor-default:8080
      - FALLBACK_URL=http://payment-processor-fallback:8080
      - DB_NAME=banco.fdb
      - DB_USER=SYSDBA
      - DB_PASS=masterkey
      - DB_HOST=firebird
      - DB_PORT=3050
      - NUM_WORKERS=32
      - NUM_TENTATIVAS_DEFAULT=3
      - READ_TIME_OUT=3000
      - TEMPO_FILA=1000
      - DEBUG=N
    volumes: #somente descomentar se ativar DEBUG
      - ./Logs/:/opt/rinha/Logs/
    networks:
      - backend-rinha
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: "90MB"

  api2:
    <<: *api
    hostname: api2
    volumes: #somente descomentar se ativar DEBUG
      - ./Logs2/:/opt/rinha/Logs/

  firebird:
    image: firebirdsql/firebird
    container_name: rinha-firebird
    ports:
      - "3050:3050"
    environment:
      - FIREBIRD_ROOT_PASSWORD=masterkey
      - FIREBIRD_USER=SYSDBA
      - FIREBIRD_PASSWORD=masterkey
      - FIREBIRD_DATABASE=banco.fdb
      #- FIREBIRD_DATABASE_PAGE_SIZE=16384
      - FIREBIRD_DATABASE_DEFAULT_CHARSET=UTF8
      - FIREBIRD_CONF_DataTypeCompatibility=3.0
      #- FIREBIRD_CONF_ConnectionPoolSize=300
      #- FIREBIRD_CONF_DefaultDbCachePages=4096
      #- FIREBIRD_CONF_LockMemSize=1048576
      #- FIREBIRD_CONF_TempCacheLimit=67108864
      #- FIREBIRD_CONF_MaxUnflushedWrites=20
      #- FIREBIRD_CONF_MaxUnflushedWriteTime=2

    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend-rinha
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "150MB"

networks:
  backend-rinha:
    name: backend-rinha
    driver: bridge
  payment-processor:
    external: true
